---
version: '3.8'
x-logging: &default-logging
  driver: json-file
  options:
    max-size: 10m
    max-file: '5'
x-healthcheck: &default-healthcheck
  test: [CMD, curl, -f, http://localhost:9083/version]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 5s
services:
  strictdoc:
    build:
      context: .
      args:
        APP_IMAGE_VERSION: 1.0.0-test
    image: strictdoc_service:test
    container_name: strictdoc_service_test
    restart: unless-stopped
    read_only: true
    security_opt: [no-new-privileges:true]
    cap_drop: [ALL]
    ports: [9083:9083]
    environment: [LOG_LEVEL=INFO]
    healthcheck: *default-healthcheck
    logging: *default-logging
    volumes:
      - type: tmpfs
        target: /tmp
    networks: [strictdoc-network]
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
networks:
  strictdoc-network:
    driver: bridge
